// <auto-generated />
using System;
using LanchesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LanchesAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210430233000_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("LanchesAPI.Data.Adicional", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Lancheid")
                        .HasColumnType("int");

                    b.Property<int>("idIngrediente")
                        .HasColumnType("int");

                    b.Property<int>("idLanche")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Lancheid");

                    b.ToTable("adicionais");

                    b.HasData(
                        new
                        {
                            id = 1,
                            idIngrediente = 2,
                            idLanche = 1
                        },
                        new
                        {
                            id = 2,
                            idIngrediente = 3,
                            idLanche = 1
                        },
                        new
                        {
                            id = 3,
                            idIngrediente = 5,
                            idLanche = 1
                        },
                        new
                        {
                            id = 4,
                            idIngrediente = 3,
                            idLanche = 2
                        },
                        new
                        {
                            id = 5,
                            idIngrediente = 5,
                            idLanche = 2
                        },
                        new
                        {
                            id = 6,
                            idIngrediente = 3,
                            idLanche = 3
                        },
                        new
                        {
                            id = 7,
                            idIngrediente = 4,
                            idLanche = 3
                        },
                        new
                        {
                            id = 8,
                            idIngrediente = 5,
                            idLanche = 3
                        },
                        new
                        {
                            id = 9,
                            idIngrediente = 2,
                            idLanche = 4
                        },
                        new
                        {
                            id = 10,
                            idIngrediente = 3,
                            idLanche = 4
                        },
                        new
                        {
                            id = 11,
                            idIngrediente = 4,
                            idLanche = 4
                        },
                        new
                        {
                            id = 12,
                            idIngrediente = 5,
                            idLanche = 4
                        });
                });

            modelBuilder.Entity("LanchesAPI.Data.Ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.ToTable("ingredientes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Salada",
                            preco = 0m
                        },
                        new
                        {
                            id = 2,
                            nome = "Bacon",
                            preco = 0m
                        },
                        new
                        {
                            id = 3,
                            nome = "Hambúrger de Carne",
                            preco = 0m
                        },
                        new
                        {
                            id = 4,
                            nome = "Ovo",
                            preco = 0m
                        },
                        new
                        {
                            id = 5,
                            nome = "Queijo",
                            preco = 0m
                        });
                });

            modelBuilder.Entity("LanchesAPI.Data.Lanche", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("id");

                    b.ToTable("Lanches");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "X-Bacon"
                        },
                        new
                        {
                            id = 2,
                            nome = "X-Burger"
                        },
                        new
                        {
                            id = 3,
                            nome = "X-Egg"
                        },
                        new
                        {
                            id = 4,
                            nome = "X-Egg Bacon"
                        });
                });

            modelBuilder.Entity("LanchesAPI.Data.Adicional", b =>
                {
                    b.HasOne("LanchesAPI.Data.Lanche", null)
                        .WithMany("adicionais")
                        .HasForeignKey("Lancheid");
                });

            modelBuilder.Entity("LanchesAPI.Data.Lanche", b =>
                {
                    b.Navigation("adicionais");
                });
#pragma warning restore 612, 618
        }
    }
}
